#include <mpi.h>
#include <cuda_runtime.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

enum { S=0, B=1, F=2 };
typedef struct { uint32_t n,degree,ticks,sample,source,preview; uint64_t seed; double alpha,beta,verify,forget; } Config;
typedef struct { uint64_t edges,*offset; uint32_t *adj; } Graph;

#define CUDA_OK(call) do { cudaError_t e=(call); if(e!=cudaSuccess) { fprintf(stderr,"CUDA: %s\n",cudaGetErrorString(e)); MPI_Abort(MPI_COMM_WORLD,2); } } while(0)
static void *xmalloc(size_t n){void*p=malloc(n);if(!p){fprintf(stderr,"Out of memory (%zu bytes)\n",n);MPI_Abort(MPI_COMM_WORLD,3);}return p;}
__host__ __device__ static uint64_t mix64(uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
__host__ __device__ static double rnd(uint64_t seed,uint32_t tick,uint32_t node,uint32_t stream){uint64_t k=seed^((uint64_t)tick*0xd6e8feb86659fd93ULL)^((uint64_t)node*0xa5a3564e27f8862bULL)^((uint64_t)stream*0x9e3779b97f4a7c15ULL);return (double)(mix64(k)>>11)*(1.0/9007199254740992.0);}

static Config args(int argc,char**argv){Config c={10000,6,300,1,0,180,42,.3,.5,.05,.1};for(int i=1;i+1<argc;i+=2){char*k=argv[i],*v=argv[i+1];if(!strcmp(k,"--nodes"))c.n=strtoul(v,0,10);else if(!strcmp(k,"--mean-degree"))c.degree=strtoul(v,0,10);else if(!strcmp(k,"--ticks"))c.ticks=strtoul(v,0,10);else if(!strcmp(k,"--sample-every"))c.sample=strtoul(v,0,10);else if(!strcmp(k,"--source-node"))c.source=strtoul(v,0,10);else if(!strcmp(k,"--preview-nodes"))c.preview=strtoul(v,0,10);else if(!strcmp(k,"--alpha"))c.alpha=strtod(v,0);else if(!strcmp(k,"--beta"))c.beta=strtod(v,0);else if(!strcmp(k,"--verify"))c.verify=strtod(v,0);else if(!strcmp(k,"--forget"))c.forget=strtod(v,0);else if(!strcmp(k,"--seed"))c.seed=strtoull(v,0,10);}if(c.n<4||c.source>=c.n||c.sample<1){fprintf(stderr,"Invalid configuration\n");MPI_Abort(MPI_COMM_WORLD,4);}if(c.preview>c.n)c.preview=c.n;return c;}

static Graph make_graph(uint32_t n,uint32_t degree,uint64_t seed){uint32_t m=degree/2;if(m<1)m=1;if(m>=n)m=n-1;uint32_t first=m+1;uint64_t cap=(uint64_t)first*(first-1)/2+(uint64_t)(n-first)*m,e=0,pooln=0;uint32_t*u=(uint32_t*)xmalloc(cap*4),*v=(uint32_t*)xmalloc(cap*4),*pool=(uint32_t*)xmalloc(cap*8),*pick=(uint32_t*)xmalloc(m*4);for(uint32_t a=0;a<first;a++)for(uint32_t b=a+1;b<first;b++){u[e]=a;v[e++]=b;pool[pooln++]=a;pool[pooln++]=b;}uint64_t r=seed;for(uint32_t node=first;node<n;node++){for(uint32_t j=0;j<m;j++){uint32_t q;int dup;do{r=mix64(r);q=pool[r%pooln];dup=0;for(uint32_t k=0;k<j;k++)dup|=pick[k]==q;}while(dup);pick[j]=q;u[e]=node;v[e++]=q;pool[pooln++]=node;pool[pooln++]=q;}}free(pool);free(pick);Graph g={e,(uint64_t*)calloc((size_t)n+1,8),(uint32_t*)xmalloc(e*8)};if(!g.offset)MPI_Abort(MPI_COMM_WORLD,3);for(uint64_t i=0;i<e;i++){g.offset[u[i]+1]++;g.offset[v[i]+1]++;}for(uint32_t i=1;i<=n;i++)g.offset[i]+=g.offset[i-1];uint64_t*cur=(uint64_t*)xmalloc(n*8);memcpy(cur,g.offset,n*8);for(uint64_t i=0;i<e;i++){g.adj[cur[u[i]]++]=v[i];g.adj[cur[v[i]]++]=u[i];}free(cur);free(u);free(v);return g;}

__global__ static void step_kernel(const uint64_t*off,const uint32_t*adj,const uint8_t*cur,uint8_t*next,uint32_t begin,uint32_t count,uint32_t tick,uint64_t seed,double alpha,double beta,double verify,double forget){uint32_t local=blockIdx.x*blockDim.x+threadIdx.x;if(local>=count)return;uint32_t node=begin+local;uint8_t state=cur[node],out=state;if(state==S){uint32_t nb=0,nf=0;for(uint64_t p=off[node];p<off[node+1];p++){uint8_t q=cur[adj[p]];nb+=q==B;nf+=q==F;}double wb=nb*(1.0+alpha),wf=nf*(1.0-alpha),den=wb+wf;if(den>0){double r=rnd(seed,tick,node,0),pb=beta*wb/den,pf=beta*wf/den;if(r<pb)out=B;else if(r<pb+pf)out=F;}}else if(state==B){if(rnd(seed,tick,node,0)<forget)out=S;else if(rnd(seed,tick,node,1)<verify)out=F;}else if(rnd(seed,tick,node,0)<forget)out=S;next[node]=out;}

static void emit(uint32_t tick,uint64_t s,uint64_t b,uint64_t f,uint64_t reached,uint64_t peak,uint32_t peakTick,double elapsed,const uint8_t*state,uint32_t preview){printf("{\"kind\":\"progress\",\"tick\":%u,\"susceptible\":%llu,\"believers\":%llu,\"factCheckers\":%llu,\"reached\":%llu,\"maxBelievers\":%llu,\"maxBelieversTick\":%u,\"elapsedSeconds\":%.6f,\"previewStates\":[",tick,(unsigned long long)s,(unsigned long long)b,(unsigned long long)f,(unsigned long long)reached,(unsigned long long)peak,peakTick,elapsed);for(uint32_t i=0;i<preview;i++)printf("%s%u",i?",":"",state[i]);puts("]}");fflush(stdout);}

int main(int argc,char**argv){MPI_Init(&argc,&argv);int rank,size;MPI_Comm_rank(MPI_COMM_WORLD,&rank);MPI_Comm_size(MPI_COMM_WORLD,&size);Config c=args(argc,argv);int devices=0;CUDA_OK(cudaGetDeviceCount(&devices));if(devices<1){fprintf(stderr,"No CUDA GPU visible\n");MPI_Abort(MPI_COMM_WORLD,5);}CUDA_OK(cudaSetDevice(rank%devices));MPI_Barrier(MPI_COMM_WORLD);double total0=MPI_Wtime(),graph0=MPI_Wtime();Graph g={0,0,0};if(rank==0)g=make_graph(c.n,c.degree,c.seed);MPI_Bcast(&g.edges,1,MPI_UNSIGNED_LONG_LONG,0,MPI_COMM_WORLD);if(rank){g.offset=(uint64_t*)xmalloc(((size_t)c.n+1)*8);g.adj=(uint32_t*)xmalloc((size_t)g.edges*8);}MPI_Bcast(g.offset,c.n+1,MPI_UNSIGNED_LONG_LONG,0,MPI_COMM_WORLD);MPI_Bcast(g.adj,(int)(2*g.edges),MPI_UNSIGNED,0,MPI_COMM_WORLD);double graphSecs=MPI_Wtime()-graph0;
  int*counts=(int*)xmalloc(size*4),*displs=(int*)xmalloc(size*4);for(int r=0;r<size;r++){uint32_t a=(uint64_t)c.n*r/size,z=(uint64_t)c.n*(r+1)/size;counts[r]=(int)(z-a);displs[r]=(int)a;}uint32_t begin=displs[rank],count=counts[rank];uint8_t*host=(uint8_t*)calloc(c.n,1),*local=(uint8_t*)xmalloc(count),*seen=(uint8_t*)calloc(count,1);host[c.source]=B;if(c.source>=begin&&c.source<begin+count)seen[c.source-begin]=1;
  uint64_t *doff;uint32_t*dadj;uint8_t*dcur,*dnext;CUDA_OK(cudaMalloc((void**)&doff,((size_t)c.n+1)*8));CUDA_OK(cudaMalloc((void**)&dadj,(size_t)g.edges*8));CUDA_OK(cudaMalloc((void**)&dcur,c.n));CUDA_OK(cudaMalloc((void**)&dnext,c.n));CUDA_OK(cudaMemcpy(doff,g.offset,((size_t)c.n+1)*8,cudaMemcpyHostToDevice));CUDA_OK(cudaMemcpy(dadj,g.adj,(size_t)g.edges*8,cudaMemcpyHostToDevice));CUDA_OK(cudaMemcpy(dcur,host,c.n,cudaMemcpyHostToDevice));uint64_t reached=1,peak=1;uint32_t peakTick=0;if(rank==0)emit(0,c.n-1,1,0,reached,peak,peakTick,0,host,c.preview);MPI_Barrier(MPI_COMM_WORLD);double sim0=MPI_Wtime();
  uint64_t finalS=0,finalB=1,finalF=0;for(uint32_t tick=1;tick<=c.ticks;tick++){step_kernel<<<(count+255)/256,256>>>(doff,dadj,dcur,dnext,begin,count,tick,c.seed,c.alpha,c.beta,c.verify,c.forget);CUDA_OK(cudaGetLastError());CUDA_OK(cudaMemcpy(local,dnext+begin,count,cudaMemcpyDeviceToHost));uint64_t lc[4]={0,0,0,0};for(uint32_t i=0;i<count;i++){lc[local[i]]++;if(local[i]!=S&&!seen[i]){seen[i]=1;lc[3]++;}}uint64_t gc[4]={0,0,0,0};MPI_Reduce(lc,gc,4,MPI_UNSIGNED_LONG_LONG,MPI_SUM,0,MPI_COMM_WORLD);MPI_Allgatherv(local,count,MPI_UNSIGNED_CHAR,host,counts,displs,MPI_UNSIGNED_CHAR,MPI_COMM_WORLD);CUDA_OK(cudaMemcpy(dcur,host,c.n,cudaMemcpyHostToDevice));if(rank==0){reached+=gc[3];finalS=gc[S];finalB=gc[B];finalF=gc[F];if(finalB>peak){peak=finalB;peakTick=tick;}if(tick%c.sample==0||tick==c.ticks)emit(tick,finalS,finalB,finalF,reached,peak,peakTick,MPI_Wtime()-sim0,host,c.preview);}}
  MPI_Barrier(MPI_COMM_WORLD);double simSecs=MPI_Wtime()-sim0,totalSecs=MPI_Wtime()-total0;if(rank==0){printf("{\"kind\":\"summary\",\"mode\":\"hybrid\",\"nodes\":%u,\"edges\":%llu,\"ticks\":%u,\"susceptible\":%llu,\"believers\":%llu,\"factCheckers\":%llu,\"reached\":%llu,\"maxBelievers\":%llu,\"maxBelieversTick\":%u,\"graphSeconds\":%.6f,\"simulationSeconds\":%.6f,\"totalSeconds\":%.6f,\"mpiRanks\":%d,\"gpuCount\":%d,\"sourceNode\":%u,\"seed\":%llu,\"meanDegree\":%u}\n",c.n,(unsigned long long)g.edges,c.ticks,(unsigned long long)finalS,(unsigned long long)finalB,(unsigned long long)finalF,(unsigned long long)reached,(unsigned long long)peak,peakTick,graphSecs,simSecs,totalSecs,size,devices,c.source,(unsigned long long)c.seed,c.degree);fflush(stdout);}cudaFree(doff);cudaFree(dadj);cudaFree(dcur);cudaFree(dnext);free(g.offset);free(g.adj);free(host);free(local);free(seen);free(counts);free(displs);MPI_Finalize();return 0;}
